### ISSUE TITLE
Gunicorn not found

### ISSUE THREAD

**Issue by mathiasbc** [mwcraig/headcounts-web#1]
I am trying to use this repo as an example. The buildpack seems to be working fine and it installed all the dependencies in conda-requirements.txt but when it gives me:

gunicorn: not found

when trying to run the app

**Comment by mwcraig** [comment]
Would you mind pasting the output when you `git push heroku master`? This is still working on my end...

**Comment by mathiasbc** [comment]
It was my mistake, in fact it was not able to find any package previously installed by conda. I did some changes to the path and that was breaking the environment.
